spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: hagakure
        url: jdbc:mysql://127.0.0.1:3306/citizens
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format-sql: true
        show-sql: true
